modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="slave_mod"
version="1.0.0"
displayName="Slave mod od Marka"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="VD, MCreator"

[[dependencies.slave_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




